### ISSUE TITLE
Editing a line moves it to the end of the file

### ISSUE THREAD

**Issue by arjunkc** [topydo/topydo#250] opened 2018-11-17 02:30 UTC
When I edit a todo item, it moves it to the end of the todo.txt file. Is there any way I can edit the line in place? This is making it a bit difficult to manually track changes in my file if topydo keeps reordering it.

**Comment by RonCam** [comment] 2019-03-01 12:43
Each time you _ls_ a file, by design, it's resorted according to the pre-configured sort expression, unless you override that with the -s parameter.  

Try to figure out what has changed in the item, that's causing it to sort to the end of the file.  Maybe someone with more experience has a better answer, but I think there's no way you can keep a certain item in a certain place if something in the part of the item, for which the sort is 'looking', changes.  

Look for _ls_ and _sort_ expression in the documentation.

**Comment by mruwek** [comment] 2019-03-04 14:16
@arjunkc 
> When I edit a todo item, it moves it to the end of the todo.txt file.

Hey. I'm mostly responsible for code in `EditCommand.py` so I think I can respond to this. `edit` indeed "moves" edited todo items to the end of the *todo file*. It's because of the current implementation – under the hood topydo deletes "old" todo items and after that it appends the list with new ones.

> Is there any way I can edit the line in place?

Right now you have 2 possibilities to edit todo.txt in place:

1. `topydo edit` without any arguments – it will open full todo.txt file in your favourite `$EDITOR`
2. use `topydo append` for simple additions – `AppendCommand` shouldn't change position of todo item in your file.

**Comment by arjunkc** [comment] 2019-03-04 16:14
Can I change the writing mechanism by forking the project? Do you know 
which file I would have to look in?

**Comment by mruwek** [comment] 2019-03-04 19:57
> Do you know which file I would have to look in?

`edit` command is contained in [`topydo/commands/EditCommand.py`](https://github.com/bram85/topydo/blob/master/topydo/commands/EditCommand.py), but I would strongly advise to also take a look at [`TodoListBase.py`](https://github.com/bram85/topydo/blob/master/topydo/lib/TodoListBase.py), [`TodoList.py`](https://github.com/bram85/topydo/blob/master/topydo/lib/TodoList.py), and [`Todo.py`](https://github.com/bram85/topydo/blob/master/topydo/lib/Todo.py) inside **lib** folder to understand topydo's implementation choices :)

**Comment by navytux** [comment] 2020-01-22 12:01
https://github.com/bram85/topydo/pull/268 fixes edit to not move the lines.

**Comment by davesteele** [comment] 2020-10-06 10:08
Merged

**Closed** 2020-10-06 10:08 UTC

**Comment by navytux** [comment] 2020-10-06 11:19
Thanks
